imports_granularity="Crate"
use_small_heuristics="Max"
format_code_in_doc_comments=true
normalize_comments=true
normalize_doc_attributes=true
overflow_delimited_expr=true
reorder_impl_items=true
use_field_init_shorthand=true
use_try_shorthand=true
group_imports="One"
style_edition="2024"
where_single_line=true
max_width=120
