[package]
name = "year2024"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[dependencies]
anyhow = "1.0.93"
itertools = "0.13.0"
rayon = "1.10.0"
